# Our Projects {.unnumbered}

### Patient Pathways

How do patients end up in hospital? Who comes unexpectedly as an emergency? Who is advised to go by their GP? And where do people go when they’re released from hospital? Do they go straight home, or stay at a local care centre first?

We are studying patient pathways into and out of our hospitals. Knowing the answer to these questions helps tailor healthcare, which reduces stays in hospital and waits for people with scheduled care.

We’ll publish a briefing paper with our analysis combined with four other UK regions this autumn.

### Waitlists

Millions of people are waiting for NHS care, they’re waiting longer than ever, and the waitlist is growing. How do we prioritise who gets care? How should the NHS spend it’s funding to shorten waitlists?

We’ve just begun to measure the consequences of longer waitlists within the NHS. We’re determining which specialties have patients who are using the most healthcare while they’re waiting. This will let us identify patients and procedures that could be priorised (to save patient suffering and to more efficiently spend NHS resources).

### Housing and Health

Our homes affect our health. In 2025 we will be working with our local authorities to prioritise housing accomodation and support for people with serious medical conditions.  

### Children's Mental Health

We recently finished a big project working to understand inequalities in children’s mental healthcare.

Read a blog post about mental health prescribing to children. Or a post about children’s treatment by specialist mental health doctors. Check out our briefing paper for policy makers. Or wade into our academic research article.(fix links)